name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Obsidian Finance Plugin
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: I'm frustrated when... / I need to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like the plugin to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - Dashboard/Visualization
        - BQL Queries/Reporting
        - Transaction Management
        - Account Management
        - Commodity/Currency Tracking
        - File Operations
        - Settings/Configuration
        - UI/UX Improvements
        - Performance/Optimization
        - Integration/Export
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Perspective)
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but...

  - type: textarea
    id: examples
    attributes:
      label: Examples/Mockups
      description: |
        If applicable, provide examples from other tools, mockups, or code snippets that illustrate your idea.
        You can drag and drop images here.
      placeholder: Similar to how [other tool] does it... / Here's a mockup... / Example BQL query...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        As a [type of user], I want to [action] so that [benefit].
        Example: As a freelancer, I want to track invoice statuses in the journal view so that I can quickly see outstanding payments.

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'd like to implement this feature myself (with guidance)
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide additional feedback during development

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: |
        - Related features
        - Beancount syntax considerations
        - Compatibility concerns
        - Performance implications

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been requested before
          required: true
        - label: This feature aligns with the plugin's core purpose (Beancount integration in Obsidian)
          required: true
